### ISSUE TITLE
 make integration with google analitycs optional

### ISSUE THREAD

**Issue by euprogramador** [BulletTrainHQ/bullet-train-frontend#22]
frontend breaks and does not start if the GOOGLE_SERVICE_ACCOUNT integration code is not provided.

It only worked after commenting on the bullet-train-api / src / analytics / query.py integration in the get_events_for_organisation method and forcing return 0

I suggest making integration with google analitycs optional.

**Comment by matthewelwell** [comment]
Hi @euprogramador, would you be able to send a bit more information please? For example, I'm not sure what you mean by "frontend breaks and does not start". Could you send any errors, etc. that you're getting please? 

I'm a little confused by your report since the frontend doesn't rely on the GOOGLE_SERVICE_ACCOUNT environment variable, only the BE does and it is indeed optional (you can see the code to handle it [here](https://github.com/BulletTrainHQ/bullet-train-api/blob/master/src/app/settings/common.py#L44)).

Also, would you be able to confirm that you're running the latest version of the FE code, since I can see that the FE is designed to handle an error on this endpoint. You can see that code [here](https://github.com/BulletTrainHQ/bullet-train-frontend/blob/4ed9f5b698cda71a405f5e95dfc2969486da2051/common/stores/organisation-store.js#L24).

**Comment by kyle-ssg** [comment]
I think to Add to @matthewelwell's point. Indeed the frontend does need a valid setup for this to provide usage stats, however this is totally non-breaking and does not crash the frontend by any means.

For example this is what would happen if we switch out the usage endpoint for any breaking url, the frontend silently catches this for this exact reason as we don't want to be reliant on this as Google Analytics has been flaky in the past.

The worst that would happen is that you aren't provided with usage stats as can be seen here:

![image](https://user-images.githubusercontent.com/8608314/83437869-6d792080-a438-11ea-9bf2-900318e7f26c.png).

I'd suggest check that you are running both the latest frontend and backend and reopen this issue with replication steps.
